name: .NET Core Desktop

on:
  push:
    tags: 
      - '*.*.*'

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: SubconverterTools.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Set console output encoding
      run: |
        chcp 65001  # 设置控制台代码页为 UTF-8

    - name: Restore the application
      run: msbuild ${{ env.Solution_Name }} /t:Restore /p:Configuration=${{ matrix.configuration }}

    - name: Build the application
      run: msbuild ${{ env.Solution_Name }} /p:Configuration=${{ matrix.configuration }} /p:OutputPath=bin/Release /p:OutputEncoding=utf-8

    - name: Create Zip Package
      run: |
        $zipPath = "bin/Release/SubconverterTools.zip"
        Compress-Archive -Path "bin/Release/*" -DestinationPath $zipPath
      shell: pwsh

    - name: Debug List Files
      run: Get-ChildItem -Path bin/Release
      shell: pwsh

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build Artifacts
        path: bin/Release/SubconverterTools.zip
        

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release-${{ github.ref_name }}
        files: bin/Release/SubconverterTools.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
